name: Bump version
on:
  push:
    branches:
      - master
      
jobs:
  bump:
    name: Bumping version
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout happened
        run: echo "Checkout happened"
        
      - name: Install
        run: npm install
      - name: Install happened
        run: echo "Install happened"
        
      - name: Bump version
        run: npm run release
      - name: Bump happened
        run: echo "Bump happened"

      - name: Push changes
        run: git push gh-origin HEAD:master --tags
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
