name: Bump version
on:
  push:
    branches:
      - master
      
jobs:
  bump:
    name: Bumping version
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install
        run: npm install
        
      - name: Bump version
        run: npm run release

      - name: Push changes
        run: git push gh-origin HEAD:master --tags
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
