name: Publish npm
on:
  push:
    branches:
      - master
      
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        
      - name: Install
        run: npm install

      - name: Bump version
        run: npm run release

      - name: Push changes
        run: git push gh-origin HEAD:master --tags
        env:
            CI: true
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
