#GITHUB_TOKEN = private github token (hvilke premissions)

name: Bump version
on:
  push:
    branches:
      - master

jobs:
  bump:
    name: Bumping version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install
        run: npm install

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Bump version
        runs:
          using: "node12"
          main: "index.js"

      - name: Push
        run: git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
