name: Publish npm
on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        
    - name: Install
      run: npm install
        
    - name: Bump version
      run: |
        npm run release
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }
